export * from './abono.repository';
export * from './cliente.repository';
export * from './credito.repository';
export * from './inventario-existencias.repository';
export * from './orden-pro.repository';
export * from './orden-productos.repository';
export * from './proveedores.repository';
export * from './venta-detalle.repository';
export * from './ventas.repository';
